config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "road_trips#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :road_trips, only: [:index, :show, :new, :create, :edit, :update] do
    resources :points, only: [:new, :create]
  end
  get "/profile", to: "pages#profile", as: :profile # correspond à la show du current_user, le path : profile_path
  # get "/road_trips/search", to: "road_trips#search", as: :search # le path : search_path
  post "/participations/:id/validate", to: "participations#validate", as: :validate # le path : validate_path
  get "/road_trips/:id/details", to: "road_trips#show_details", as: :your_road_trip
  # Defines the root path route ("/")
  # root "articles#index"
  get "/road_trips/:road_trip_id/participations", to: "participations#create", as: :road_trip_participations

  get "/damien", to: "pages#damien", as: :damien

  resources :participations, only: :destroy do
    member do
      patch "accept"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :road_trip
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :road_trip
  geocoded_by :city
  after_validation :geocode, if: :will_save_change_to_city?
end

app/models/road_trip.rb
class RoadTrip < ApplicationRecord
  belongs_to :user
  has_many :points
  accepts_nested_attributes_for :points, reject_if: :all_blank, allow_destroy: true
  has_many :participations
  has_one_attached :photo
  validates :title, :photo, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :road_trips
  has_many :participations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_notifications, :user_trips, :my_participations

  def set_notifications
    if current_user
      @user = current_user
      @user_road_trips = @user.road_trips

      @pending_participations = []
      @user_road_trips.each do |road_trip|
        road_trip.participations.each do |participation|
          @pending_participations << participation if participation.validated == false
        end
      end
    end
  end

  def user_trips
    if current_user
      @user_road_trips = current_user.road_trips
    end
  end

  def my_participations
    if current_user
      @my_participations = current_user.participations
    end
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def profile
    @user = current_user
  end

  def damien
    @damienuser = User.find_by(first_name: "Damien")
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  def create
    @participation = Participation.new(road_trip: RoadTrip.find(params[:road_trip_id]))
    @participation.validated = false
    @participation.user = current_user
    @participation.save
    redirect_to road_trip_path(params[:road_trip_id])
  end

  def accept
    @participation = Participation.find(params[:id])
    @participation.update(validated: true)
    redirect_to your_road_trip_path(@participation.road_trip)
  end

  def destroy
    @participation = Participation.find(params[:id])
    @participation.destroy
    redirect_to root_path
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
#   def create
#     @point = Point.new(point_params)
#     if @point.save
#       redirect_to road_trip_path(@point)
#     else
#       render :new, status: :unprocessable_entity
#     end
#   end

#   private

# ef point_params
# params.require(:point).permit()
end

app/controllers/road_trips_controller.rb
class RoadTripsController < ApplicationController
  def index
    if params[:destination] || params[:departure]
      @road_trips = RoadTrip.joins(:points).where('points.city' => params[:destination])
                            .or(RoadTrip.joins(:points).where('points.country' => params[:destination]))
                            .or(RoadTrip.joins(:points).where('points.continent' => params[:destination]))
                            .or(RoadTrip.joins(:points).where('points.start_date' => params[:departure]))
    else
      @road_trips = RoadTrip.all
    end
    @points = Point.geocoded
    @markers = @points.map do |point|
      {
        lat: point.latitude,
        lng: point.longitude,
        info_window: render_to_string(partial: "info_window", locals: {point: point})
      }
    end
  end

  def show
    @road_trip = RoadTrip.find(params[:id])
    @points = @road_trip.points.geocoded
    @markers = @points.map do |point|
      {
        lat: point.latitude,
        lng: point.longitude
      }
    end
    @road_trips = RoadTrip.all
    participations = Participation.where(road_trip: @road_trip, user: current_user)
    @participation = participations.empty? ? nil : participations.first
  end

  # def show
  #   @road_trips = RoadTrip.find(params[:id])
  #   @points = Point.new()
  #   @markers =
  #   [
  #     {
  #       lat: @road_trip.geocode[0],
  #       lng: @road_trip.geocode[1]
  #     }
  #   ]
  # end

  def show_details
    @road_trip = RoadTrip.find(params[:id])
    @points = @road_trip.points
    @markers = @points.geocoded.map do |point|
      {
        lat: point.latitude,
        lng: point.longitude
      }
    end
  end

  def new
    @road_trip = RoadTrip.new
    @point = Point.new
  end

  def create
    @road_trip = RoadTrip.new(road_trip_params)
    @road_trip.user = current_user
    # @road_trip.save
    # points = params[:points].values
    # points.each do |point_hash|
    #   new_point = Point.new(point_hash)
    #   new_point.road_trip = @road_trip
    #   new_point.save
    # end
    if @road_trip.save
      redirect_to road_trips_path(@road_trip)
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
  end

  def update
  end

  private

  def road_trip_params
    params.require(:road_trip).permit(:photo, :title, :description, :native_language, :other_language, :work, :number_participants, points_attributes: [:latitude, :longitude, :city, :country, :continent, :start_date, :end_date, :description, :budget_day, :local_language, :currency, :housing_type, :visits_activities])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src='https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css' rel='stylesheet' />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "favicon.png", rel: "icon", type: "image/png" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>

    <%= render "shared/banner" %>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>

    <%= render "shared/footer" %>


  </body>
</html>

app/views/pages/damien.html.erb
<div class="container">
  <h3 class="road-trip-title"><%= @damienuser.first_name + " " + @damienuser.last_name %></h3>
  <div class="profile-header">
    <h1 class="road-trips-title h1-welcome">Welcome to my page</h1>
    <div class="div-avatar avatar-current-user">
        <img src="https://res.cloudinary.com/debuijcke/image/upload/v1670325378/Road_trip_avatar_photos/Billie_road_tripper_avatar_ze3qs5.jpg" class="avatar-perso";
        alt="Avatar" />
      </div>
        <h5 class="nickname">Nick name</h5>
          <div class="nickname-user">
            <%= @damienuser.nickname %>
          </div>
      </div>
  <div class="container-description-profile">
  <div class="p-description">
    <div>
      <%= @damienuser.about_yourself %>
    </div>
    <div>
      <%= @damienuser.expect_experience %>
    </div>
    <div>
      <%= @damienuser.passion %>
    </div>
    <div>
      <%= @damienuser.free_time %>
    </div>
  </div>
  </div>


<div class="user-profile-wrapper">


 <div class="user-profile-informations">

    <div class="information-title">
      <h4>My personal informations</h5>
    </div>

    <div class="user-informations">
      <div>
        <h5>Date of birth</h5>
        <p class="text-profile-user"><%= @damienuser.date_of_birth %></p>
      </div>
      <div>
        <h5>Faculty</h5>
        <p class="text-profile-user"><%= @damienuser.study_field %></p>
      </div>
      <div>
        <h5>University</h5>
        <p class="text-profile-user"><%= @damienuser.university %></p>
      </div>
      <div>
        <h5>Country</h5>
        <p class="text-profile-user"><%= @damienuser.country %></p>
      </div>
      <div>
        <h5>State</h5>
        <p class="text-profile-user"><%= @damienuser.state %></p>
      </div>
    </div>

    <div class="user-email">
      <h5>E-Mail</h5>
          <p><%= @damienuser.university_email %></p>
      <p class="text-profile-user">damien.peres@cours-florent.fr</p>
    </div>

  </div>

  <div class="user-profile-road-trip">
      <h4>My Road Trips</h4>
    </div>
</div>
  <%# <%= @damienuser.city %>
  <%# <%= @damienuser.password %>
  <div class="carousel-profile">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item  carousel-profile active">
        <img src="https://images.pexels.com/photos/629142/pexels-photo-629142.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="The tower Pisa">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/2609463/pexels-photo-2609463.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="On the mounteens">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/984868/pexels-photo-984868.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="Palmes">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/3830890/pexels-photo-3830890.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="Venise">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/6140458/pexels-photo-6140458.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="The best friends">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/3756158/pexels-photo-3756158.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="Walking">
      </div>
      <div class="carousel-item ">
        <img src="https://images.pexels.com/photos/3935702/pexels-photo-3935702.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="On the road">
      </div>
  </div>
</div>



  </div>

</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/profile.html.erb
<div class="container">
  <h3 class="road-trip-title"><%= @user.first_name + " " + @user.last_name %></h3>
  <div class="profile-header">
    <h1 class="road-trips-title h1-welcome">Welcome to my page</h1>
    <div class="div-avatar avatar-current-user">
        <img src="https://res.cloudinary.com/debuijcke/image/upload/v1670325378/Road_trip_avatar_photos/Billie_road_tripper_avatar_ze3qs5.jpg" class="avatar-perso";
        alt="Avatar" />
      </div>
        <h5 class="nickname">Nick name</h5>
          <div class="nickname-user">
            <%= @user.nickname %>
          </div>
      </div>
  <div class="container-description-profile">
  <div class="p-description">
    <div>
      <%= @user.about_yourself %>
    </div>
    <div>
      <%= @user.expect_experience %>
    </div>
    <div>
      <%= @user.passion %>
    </div>
    <div>
      <%= @user.free_time %>
    </div>
  </div>
  </div>


<div class="user-profile-wrapper">


 <div class="user-profile-informations">

    <div class="information-title">
      <h4>My personal informations</h5>
    </div>

    <div class="user-informations">
      <div>
        <h5>Date of birth</h5>
        <p class="text-profile-user"><%= @user.date_of_birth %></p>
      </div>
      <div>
        <h5>Faculty</h5>
        <p class="text-profile-user"><%= @user.study_field %></p>
      </div>
      <div>
        <h5>University</h5>
        <p class="text-profile-user"><%= @user.university %></p>
      </div>
      <div>
        <h5>Country</h5>
        <p class="text-profile-user"><%= @user.country %></p>
      </div>
      <div>
        <h5>State</h5>
        <p class="text-profile-user"><%= @user.state %></p>
      </div>
    </div>

    <div class="user-email">
      <h5>E-Mail</h5>
          <p><%= @user.university_email %></p>
      <p class="text-profile-user">damien.peres@cours-florent.fr</p>
    </div>

  </div>

  <div class="user-profile-road-trip">
      <h4>My Road Trips</h4>
    </div>
</div>
  <%# <%= @user.city %>
  <%# <%= @user.password %>
  <div class="carousel-profile">
    <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item  carousel-profile active">
        <img src="https://images.pexels.com/photos/629142/pexels-photo-629142.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="The tower Pisa">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/2609463/pexels-photo-2609463.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="On the mounteens">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/984868/pexels-photo-984868.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="Palmes">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/3830890/pexels-photo-3830890.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="Venise">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/6140458/pexels-photo-6140458.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="The best friends">
      </div>
      <div class="carousel-item carousel-profile">
        <img src="https://images.pexels.com/photos/3756158/pexels-photo-3756158.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="Walking">
      </div>
      <div class="carousel-item ">
        <img src="https://images.pexels.com/photos/3935702/pexels-photo-3935702.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" class="d-block w-100" alt="On the road">
      </div>
  </div>
</div>



  </div>

</div>

app/views/participations/validate.html.erb
<h1>Participations#validate</h1>
<p>Find me in app/views/participations/validate.html.erb</p>

app/views/road_trips/_info_window.html.erb
<h2><%= point.country%></h2>
<p><%= point.city%></p>

app/views/road_trips/_point_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>" >
  <div>
    <%= f.label :city, class:"form-label label-style-point" %>
    <%= f.text_field :city, class:"form-control space-style-city" %>
  </div>

  <div data-controller="flatpickr" class="my-3 div-flex">
      <div>
        <%= f.label :arrival, class:"form-label label-style-point" %>
        <%= f.text_field :start_date, data: { flatpickr_target: "startDate" }, class:"space-style-step1"  %>
      </div>
      <div>
        <%= f.label :departure, class:"form-label label-style-point" %>
        <%= f.text_field :end_date, data: { flatpickr_target: "endDate" }, class:"space-style-step1" %>
      </div>
  </div>

  <% if false %>
    <%= f.label :description, class:"form-label label-style-point" %>
    <%= f.text_field :description, class:"form-control" %>
    <%= f.label :budget_day, class:"form-label label-style-point" %>
    <%= f.text_field :budget_day, class:"form-control" %>
    <%= f.label :local_language, class:"form-label label-style-point" %>
    <%= f.text_field :local_language, class:"form-control space-style-step2" %>
  <% end %>

  <div>
    <%= f.label "local currency", class:"form-label label-style-point" %>
    <%= f.text_field :currency, class:"form-control space-style-city" %>
  </div>

  <div class="div-flex">
    <div class="custom-control custom-switch form-check form-switch">
      <%= f.label "activities", class:"form-label label-style-point custom-control-label form-check-label", for:"customSwitch1" %>
      <div class="">
        <i class="fa-solid fa-building-columns"></i>
        <%= f.check_box :visits_activities, class:"form-check-input custom-control-input", id:"customSwitch1" %>
      </div>
      <div class="">
        <i class="fa-solid fa-masks-theater"></i>
        <%= f.check_box :visits_activities, class:"form-check-input custom-control-input", id:"customSwitch1" %>
      </div>
      <div class="">
        <i class="fa-solid fa-champagne-glasses"></i>
        <%= f.check_box :visits_activities, class:"form-check-input custom-control-input", id:"customSwitch1" %>
      </div>
      <div class="">
        <i class="fa-solid fa-person-hiking"></i>
        <%= f.check_box :visits_activities, class:"form-check-input custom-control-input", id:"customSwitch1" %>
      </div>
      <div class="">
        <i class="fa-solid fa-umbrella-beach"></i>
        <%= f.check_box :visits_activities, class:"form-check-input custom-control-input", id:"customSwitch1" %>
      </div>
    </div>

    <div class="custom-control custom-switch form-check form-switch">
      <%= f.label "accomodations", class:"form-label label-style-point custom-control-label form-check-label", for:"customSwitch1" %>
      <div class="">
        <i class="fa-solid fa-hotel"></i>
        <%= f.check_box :housing_type, class:"form-check-input custom-control-input", id:"customSwitch1" %>
      </div>
      <div class="">
        <i class="fa-solid fa-bed"></i>
        <%= f.check_box :housing_type, class:"form-check-input custom-control-input", id:"customSwitch1" %>
      </div>
      <div class="">
        <i class="fa-brands fa-airbnb"></i>
        <%= f.check_box :housing_type, class:"form-check-input custom-control-input", id:"customSwitch1" %>
      </div>
      <div class="">
        <i class="fa-solid fa-campground"></i>
        <%= f.check_box :housing_type, class:"form-check-input custom-control-input", id:"customSwitch1" %>
      </div>
    </div>
  </div>

  <div class="div-btn-remove">
    <button type="button" data-action="nested-form#remove" class="btn-remove">Remove point</button>
  </div>

  <%= f.hidden_field :_destroy %>
</div>

app/views/road_trips/_road_trip_card.html.erb
  <div class="card-home position-relative">
    <div>
      <% if road_trip.photo.attached? %>
        <%= link_to road_trip_path(road_trip), class:"card-name" do %>
          <%= cl_image_tag road_trip.photo.key, height: 400, width: 600, crop: :fill %>
        <% end %>
      <% end %>
    </div>
    <div class="card-text position-absolute top-50 start-50 translate-middle">
      <h4><%= link_to road_trip_path(road_trip), class:"card-name" do %>
        <%= road_trip.title %></h4>
      <% end %>
    </div>
  </div>

app/views/road_trips/edit.html.erb
<h1>RoadTrips#edit</h1>
<p>Find me in app/views/road_trips/edit.html.erb</p>

app/views/road_trips/index.html.erb
<% #content_for :meta_title, "#{@offer.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% #content_for :meta_description, @offer.description %>
<% #content_for :meta_image, cl_image_path(@offer.photo.path) %>

<div class="container-white">

  <div>
  </div>

  <div class="container-search">
    <%= form_with url: road_trips_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :destination,
      params[:destination],
      class: "form-control",
      placeholder: "Enter a destination"
    %>
    <%= date_field_tag :departure,
      params[:departure],
      class: "form-control",
      placeholder: ""
    %>
    <%= submit_tag "Search", class: "btn-gradient" %>
    <% end %>
  </div>

  <div class="container-home">
    <% @road_trips.each do |road_trip| %>
      <%= render 'road_trip_card',  road_trip: road_trip %>
    <% end %>
  </div>
</div>

app/views/road_trips/show.html.erb
<div class="container-white">
  <h1 class="road-trip-title"><%= @road_trip.title %></h1>

<div class="div-avatar">
  <img src="https://res.cloudinary.com/debuijcke/image/upload/v1670325408/Road_trip_avatar_photos/Julia_road_trip_avatar_y6cwdk.jpg" class="avatar-perso";
  alt="Avatar" />
  <img src="https://res.cloudinary.com/debuijcke/image/upload/v1670325378/Road_trip_avatar_photos/Billie_road_tripper_avatar_ze3qs5.jpg" class="avatar-perso";
  alt="Avatar" />
</div>
  <%= image_tag @road_trip.photo, class: "trip-image" %>
  <div class="description-container">
    <div class="p-description">
      <p><%= @road_trip.description %>"</p>
    </div>
    <div class="p-description-user-signature">
      <p><%= @road_trip.user.first_name %>.</p>
    </div>
  </div>

  <div class="road-trip-show-details-container">
    <div>
      <h4>Route details</h4>
    </div>
    <div class="route-info-container">
        <div><h5>Continent</h5>
        <% @points.each do |point| %>
            <p><%= point.continent %></p>
           <% end %>
        </div>
        <div><h5>Country</h5>
        <% @points.each do |point| %>
            <p><%= point.country %></p>
           <% end %>
        </div>
        <div><h5>City</h5>
        <% @points.each do |point| %>
            <p><%= point.city %>
           <% end %>
        </div>
        <div><h5>Arrival</h5>
        <% @points.each do |point| %>
            <p><%= point.start_date %></p>
           <% end %>
        </div>
        <div><h5>Departure</h5>
        <% @points.each do |point| %>
            <p><%= point.end_date %></p>
           <% end %>
        </div>
    </div>
    <div class="other-info-container">
      <h5>Spoken languages in the group</h5>
        <p><%= @road_trip.native_language %></p>
        <p><%= @road_trip.other_language %></p>
    </div>
  </div>

  <div>
    <% if @participation == nil %>
    <%= link_to "I want to participate !", road_trip_participations_path(@road_trip), class:"btn-participation" %>
    <% end %>
  </div>

  <div class="carousel-profile">
    <div id="carouselExampleControls" class="carousel slide carousel-perso" data-bs-ride="carousel">
      <div class="carousel-inner">
        <% @road_trips.each_with_index do |road_trip, i| %>
          <div class="carousel-item <%= i == 0 ? 'active' : '' %>">
            <%= render 'road_trip_card',  road_trip: road_trip %>
          </div>
        <% end %>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>
</div>

app/views/road_trips/update.html.erb
<h1>RoadTrips#update</h1>
<p>Find me in app/views/road_trips/update.html.erb</p>

app/views/shared/_footer.html.erb
  <div class="footer font-foot">
    <div class="footer-links footer-links a:hover">
      <p>Share your best photos with us!</p>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <%# <a href="#"><i class="fab fa-facebook"></i></a> %>
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-bold navbar-lewagon">
      <ul class="navbar-nav d-flex justify-content-around w-100">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Plan a road trip", new_road_trip_path, class: "nav-link" %>
          </li>
          <div class="dropdown">
            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.first_name %>
            </a>

            <ul class="dropdown-menu menu-width" aria-labelledby="dropdownMenuLink">
              <li><a class="dropdown-item" href="#"><%= link_to "My profile", profile_path%></a></li>
              <li>Pending participations :</li>
              <%= link_to "clique moi", damien_path %>
              <% @pending_participations.each do |participation| %>
                <li><%= link_to participation.user.first_name, damien_path do %>
                  asked to participate to
                  <% end %>
                  <%= link_to participation.road_trip.title, your_road_trip_path(participation.road_trip) %>
                  | <%= link_to "Accept", accept_participation_path(participation), data: {turbo_method: :patch} %>
                  / <%= link_to "Decline", participation_path(participation), data: {turbo_method: :delete} %>
                </li>
              <% end %>
              <li>My trips :</li>
              <% @user_road_trips.each do |road_trip| %>
                <li><%= link_to road_trip.title, your_road_trip_path(road_trip) %></li>
              <% end %>
              <li>My participations :</li>
              <% @my_participations.each do |participation| %>
                <li><%= link_to participation.road_trip.title, your_road_trip_path(participation.road_trip) %></li>
              <% end %>
            </ul>
          </div>
          <li class="nav-item">
            <%= link_to "Concept", "#", class: "nav-link" %>
          </li>

          <%# <li class="nav-item">
            <%= link_to "My profile", profile_path, class: "nav-link" %>
          <%# </li> %>

          <li class="nav-item">
            <%= link_to "Reviews", "#", class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
</div>